[[plugins]]
repo = 'ujihisa/vimshell-ssh'
on_ft = 'vimshell'
on_cmd = 'VimShell'

[[plugins]]
repo = 'yomi322/vim-gitcomplete'
on_ft = 'vimshell'

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_if = 1
on_source = 'unite.vim'

[[plugins]]
repo = 'Shougo/echodoc.vim'
on_event = 'CompleteDone'
hook_source = 'call echodoc#enable()'

[[plugins]]
repo = 'Shougo/unite.vim'
on_cmd = 'Unite'

[[plugins]]
repo = 'Shougo/vimfiler.vim'
depends = 'unite.vim'
on_map = {n = '<Plug>'}
on_if = "isdirectory(bufname('%'))"
on_cmd = ['VimFilerTab', 'VimFiler', 'VimFilerExplorer']

[[plugins]]
repo = 'Shougo/unite-outline'
on_source = 'unite.vim'

[[plugins]]
repo = 'hewes/unite-gtags'
on_source = 'unite.vim'

[[plugins]]
repo = 'thinca/vim-unite-history'
on_source = 'unite.vim'

[[plugins]]
repo = 'osyo-manga/unite-filetype'
on_source = 'unite.vim'

[[plugins]]
repo = 'Shougo/unite-help'
on_source = 'unite.vim'

[[plugins]]
repo = 'tsukkee/unite-tag'
on_source = 'unite.vim'

[[plugins]]
repo = 'Shougo/junkfile.vim'
on_source = 'unite.vim'
on_cmd = 'JunkFileOpen'

[[plugins]]
repo = 'ujihisa/unite-colorscheme'
on_source = 'unite.vim'

[[plugins]]
repo= 'basyura/unite-rails'
on_source = 'unite.vim'
on_ft = 'ruby'

[[plugins]]
repo = 'Shougo/vinarise.vim'
on_cmd = 'Vinarise'

[[plugins]]
repo = 'thinca/vim-quickrun'
on_map = {n = '<Plug>'}
on_cmd = 'QuickRun'

[[plugins]]
repo = 'tpope/vim-bundler'
on_cmd = ['Bundle', 'Bopen']

[[plugins]]
repo = 'kana/vim-smartchr'
on_event = 'InsertCharPre'

[[plugins]]
repo = 'thinca/vim-ref'
on_map = {n = '<Plug>'}

[[plugins]]
repo = 'yuku-t/vim-ref-ri'
on_ft = 'ruby'

[[plugins]]
repo = 'moro/vim-review'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'osyo-manga/vim-monster'
on_ft = 'ruby'

[[plugins]]
repo = 'kana/vim-tabpagecd'
on_source = 'unite.vim'

[[plugins]]
repo = 'todesking/ruby_hl_lvar.vim'
on_ft = 'ruby'

[[plugins]]
repo = 'chikatoike/concealedyank.vim'
on_map = {x = '<Plug>(operator-concealedyank)'}

[[plugins]]
repo = 'thoughtbot/vim-rspec'
on_ft = 'ruby'

[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = 'slim'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'vim-scripts/grep.vim'

[[plugins]]
repo = 'easymotion/vim-easymotion'
on_map = {n = '<Plug>'}

[[plugins]]
repo = 'kana/vim-niceblock'
on_map = {x = '<Plug>'}
