" source_rc {{{
function! s:source_rc(path, ...) abort
  let use_global = get(a:000, 0, !has('vim_starting'))
  let abspath = resolve(expand('~/.vim/rc/' . a:path . '.rc.vim'))
  if !use_global
    execute 'source' fnameescape(abspath)
    return
  endif

  " substitute all 'set' to 'setglobal'
  let content = map(readfile(abspath),
        \ 'substitute(v:val, "^\\W*\\zsset\\ze\\W", "setglobal", "")')
  " create tempfile and source the tempfile
  let tempfile = tempname()
  try
    call writefile(content, tempfile)
    execute printf('source %s', fnameescape(tempfile))
  finally
    if filereadable(tempfile)
      call delete(tempfile)
    endif
  endtry
endfunction
" }}}

" Define augroup {{{
augroup MyAutoCmd
  autocmd!
augroup END
" }}}

if has('vim_starting')
  call s:source_rc('init')
endif
call s:source_rc('encoding')
call s:source_rc('edit')
call s:source_rc('view')
call s:source_rc('filetype')
call s:source_rc('mappings')
if has('nvim')
  call s:source_rc('neovim')
endif
if IsMac()
  call s:source_rc('unix')
end
call s:source_rc('plug')

if !has('nvim')
  " Allow cursor keys in insert mode
  set esckeys
endif

" Add the g flag to search/replace by default
set gdefault

" Highlight current line
set cursorline
set cursorcolumn

call s:source_rc('ideographic-space')
call s:source_rc('search')

" Enable mouse in all modes
set mouse=a

" Show the cursor position
set ruler

" Show the current mode
set showmode

" Use relative line numbers
if exists("&relativenumber")
 set relativenumber
 au BufReadPost * set relativenumber
endif

" Start scrolling three lines before the horizontal window border
set scrolloff=3

set pastetoggle=<C-E>

call s:source_rc('diff')

" Use English help file
set helplang& helplang=en,ja

" Default home directory
let t:cwd = getcwd()

set secure

call s:source_rc('emmet')
call s:source_rc('rspec')
call s:source_rc('submode')
call s:source_rc('showmarks')
call s:source_rc('lightline')
call s:source_rc('smartchr')
call s:source_rc('toggle')
call s:source_rc('solarized')
call s:source_rc('rails')
call s:source_rc('indent-guides')
call s:source_rc('fugitive')
call s:source_rc('easy-align')
call s:source_rc('neocomplete')
call s:source_rc('tags')
call s:source_rc('deoplete')
call s:source_rc('open-browser')
call s:source_rc('operator-replace')
call s:source_rc('operator-surround')
call s:source_rc('matchit')
call s:source_rc('reek')
call s:source_rc('ale')
call s:source_rc('javascript')
call s:source_rc('javascript-libraries-syntax')
call s:source_rc('delimitmate')
call s:source_rc('fzf')
call s:source_rc('cursor')
