vim.keymap.set('n', '>', '>>')
vim.keymap.set('n', '<', '<<')
vim.keymap.set('x', '>', '>gv')
vim.keymap.set('x', '<', '<gv')

vim.keymap.set('c', '<C-a>', '<Home>')
vim.keymap.set('c', '<C-b>', '<Left>')
vim.keymap.set('c', '<C-d>', '<Del>')
vim.keymap.set('c', '<C-e>', '<End>')
vim.keymap.set('c', '<C-f>', '<Right>')
vim.keymap.set('c', '<C-n>', '<Down>')
vim.keymap.set('c', '<C-p>', '<Up>')
vim.keymap.set('c', '<C-k>', '<C-\\>e getcmdpos() == 1 ? "" : getcmdline()[:getcmdpos()-2]<CR>')
vim.keymap.set('c', '<C-y>', '<C-r>*')
vim.keymap.set('c', '<C-g>', '<C-c>')

vim.keymap.set('n', '<Space>', '[Space]')
vim.keymap.set('x', '<Space>', '[Space]', { remap = true })
vim.keymap.set({ 'n', 'x' }, ' [Space]', '<Nop>')

vim.keymap.set({ 'o', 'x' }, 'aa', 'a>')
vim.keymap.set({ 'o', 'x' }, 'ia', 'i>')
vim.keymap.set({ 'o', 'x' }, 'ar', 'a]')
vim.keymap.set({ 'o', 'x' }, 'ir', 'i]')
vim.keymap.set({ 'o', 'x' }, 'aq', 'a\'')
vim.keymap.set({ 'o', 'x' }, 'iq',  'i\'')
vim.keymap.set({ 'o', 'x' }, 'ad', 'a\"')
vim.keymap.set({ 'o', 'x' }, 'id', 'i\"')

vim.keymap.set('n', 'gU', 'gUiw')
vim.keymap.set('n', 'gu', 'guiw')

vim.keymap.set('n', '<ESC><ESC>', '<Cmd>nohlsearch<CR><ESC>')

vim.keymap.set('n', '<C-CR>', 'o<ESC>')
vim.keymap.set('n', '<C-S-CR>', 'O<ESC>')
vim.keymap.set('i', '<S-CR>', '<End><CR>')
vim.keymap.set('i', '<C-S-CR>', '<Home><CR><Up>')
vim.keymap.set('n', '<M-CR>', 'mzo<ESC>`z')
vim.keymap.set('n', '<M-S-CR>', 'mzO<ESC>`z')

vim.keymap.set('n', 's', '<Nop>')
vim.keymap.set('n', 'sj', '<C-w>j')
vim.keymap.set('n', 'sk', '<C-w>k')
vim.keymap.set('n', 'sl', '<C-w>l')
vim.keymap.set('n', 'sh', '<C-w>h')
vim.keymap.set('n', 'sJ', '<C-w>J')
vim.keymap.set('n', 'sK', '<C-w>K')
vim.keymap.set('n', 'sL', '<C-w>L')
vim.keymap.set('n', 'sH', '<C-w>H')
vim.keymap.set('n', 'sn', 'gt')
vim.keymap.set('n', 'sp', 'gT')
vim.keymap.set('n', 'sr', '<C-w>r')
vim.keymap.set('n', 's=', '<C-w>=')
vim.keymap.set('n', 'sw', '<C-w>w')
vim.keymap.set('n', 'so', '<C-w>_<C-w>|')
vim.keymap.set('n', 'sO', '<C-w>=')
vim.keymap.set('n', 'sN', '<Cmd>bn<CR>')
vim.keymap.set('n', 'sP', '<Cmd>bp<CR>')
vim.keymap.set('n', 'st', '<Cmd>tabnew<CR>')
vim.keymap.set('n', 'ss', '<Cmd>sp<CR>')
vim.keymap.set('n', 'sv', '<Cmd>vs<CR>')
vim.keymap.set('n', 'sq', '<Cmd>q<CR>')
vim.keymap.set('n', 'sQ', '<Cmd>bd<CR>')

vim.keymap.set('n', 'Y', 'y$')
vim.keymap.set('n', 'yY', 'y0')
vim.keymap.set('n', 'cC', 'c0')
vim.keymap.set('n', 'dD', 'd0')
vim.keymap.set('n', 'vv', 'V')
vim.keymap.set('n', 'V', 'v$')
vim.keymap.set('n', 'vV', 'v0')
vim.keymap.set('n', '<S-c>', 'c$')

vim.keymap.set('n', '+', '<C-a>', { remap = true })
vim.keymap.set('n', '-', '<C-x>', { remap = true })

vim.keymap.set('n', '<M-k>', '<Cmd>cprevious<CR>')
vim.keymap.set('n', '<M-j>', '<Cmd>cnext<CR>')
vim.keymap.set('n', '<M-p>', '<Cmd>cprevious<CR>')
vim.keymap.set('n', '<M-n>', '<Cmd>cnext<CR>')
vim.keymap.set('n', '<M-S-p>', ':<C-u>cfirst<CR>')
vim.keymap.set('n', '<M-S-n>', ':<C-u>clast<CR>')

vim.keymap.set('n', '<Leader>w', '<Cmd>w<CR>')
vim.keymap.set('n', '<Leader>wa', '<Cmd>wall<CR>')
vim.keymap.set('n', '<Leader>wqa', '<Cmd>wqall<CR>')
vim.keymap.set('n', '<Leader>xa', '<Cmd>xall<CR>')
vim.keymap.set('n', '<Leader>qa', '<Cmd>qall!<CR>')

vim.keymap.set('t', '<ESC>', '<C-\\><C-n>')
vim.keymap.set('n', '<Leader>t', '<Cmd>terminal<CR>')
vim.keymap.set('n', '!', '<Cmd>terminal<Space><CR>')

vim.keymap.set('n', '<C-j>', '<Cmd>bprevious<CR>')
vim.keymap.set('n', '<C-k>', '<Cmd>bnext<CR>')
vim.keymap.set('c', '<C-x>', '<C-r>=expand("%:p:h")<CR>/')
