shell = "zsh"
apply = ["defer"]

[plugins.zsh-defer]
github = "romkatv/zsh-defer"
apply = ["source"]

[templates]
defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}"

[plugins.compinit]
inline = 'autoload -Uz compinit && zsh-defer compinit && compinit'

[plugins.enhancd]
github = "b4b4r07/enhancd"

[plugins.emoji-cli]
github = "b4b4r07/emoji-cli"

[plugins.ohmyzsh-lib]
github = "ohmyzsh/ohmyzsh"
dir = "lib"
use = ["{clipboard,completion,correction,directories,functions,git,grep,history,key-bindings,misc,spectrum,termsupport,theme-and-appearance}.zsh"]
apply = ["source"]

[plugins.ohmyzsh-plugins]
github = "ohmyzsh/ohmyzsh"
dir = "plugins"
use = ["{bundler/bundler,docker-compose/docker-compose,git/git,history/history,macos/macos,terraform/terraform,z/z}.plugin.zsh"]
apply = ["source"]

[plugins.ohmyzsh-plugin-docker]
github = "ohmyzsh/ohmyzsh"
dir = "plugins"
use = ["docker/_docker"]

[plugins.ohmyzsh-plugin-redis-cli]
github = "ohmyzsh/ohmyzsh"
dir = "plugins"
use = ["redis-cli/_redis-cli"]

[plugins.dotfiles]
local = "~/.zsh"
use = ["*.zsh"]
apply = ["source"]

[plugins.rbenv]
inline = 'if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi'

[plugins.plenv]
inline = 'if which plenv > /dev/null; then eval "$(plenv init -)"; fi'

[plugins.pyenv]
inline = 'if which pyenv > /dev/null; then eval "$(pyenv init --path)"; fi'

[plugins.nodenv]
inline = 'if which nodenv > /dev/null; then eval "$(nodenv init -)"; fi'

[plugins.goenv]
inline = 'if which goenv > /dev/null; then eval "$(goenv init -)"; fi'

[plugins.jenv]
inline = 'if which jenv > /dev/null; then eval "$(jenv init -)"; fi'
