[tools]
flutter = "latest"
go = "latest"
java = "latest"
node = ["latest", "lts"]
perl = "latest"
python = "latest"
ruby = "latest"
terraform = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby"]
