shell = "zsh"
apply = ["source"]

[plugins.compinit]
inline = 'autoload -Uz compinit && compinit'

[plugins.enhancd]
github = "b4b4r07/enhancd"
apply = ["source"]

[plugins.ohmyzsh-lib]
github = "ohmyzsh/ohmyzsh"
dir = "lib"
use = ["{clipboard,completion,correction,directories,functions,git,grep,history,key-bindings,misc,spectrum,termsupport,theme-and-appearance}.zsh"]
apply = ["source"]

[plugins.ohmyzsh-plugins]
github = "ohmyzsh/ohmyzsh"
dir = "plugins"
use = ["{bundler/bundler,docker-compose/docker-compose,git/git,history/history,macos/macos,terraform/terraform,z/z}.plugin.zsh"]
apply = ["source"]

[plugins.dotfiles]
local = "~/.zsh"
use = ["*.zsh"]
apply = ["source"]

[plugins.dotfiles-private]
local = "~/.zsh.private"
use = ["*.zsh"]
apply = ["source"]

[plugins.rbenv]
inline = 'if command -v rbenv > /dev/null; then eval "$(rbenv init -)"; fi'

[plugins.plenv]
inline = 'if command -v plenv > /dev/null; then eval "$(plenv init -)"; fi'

[plugins.pyenv]
inline = 'if command -v pyenv > /dev/null; then eval "$(pyenv init --path)"; fi'

[plugins.nodenv]
inline = 'if command -v nodenv > /dev/null; then eval "$(nodenv init -)"; fi'

[plugins.goenv]
inline = 'if command -v goenv > /dev/null; then eval "$(goenv init -)"; fi'

[plugins.jenv]
inline = 'if command -v jenv > /dev/null; then eval "$(jenv init -)"; fi'
