shell = "zsh"
apply = ["source"]

[plugins.compinit]
inline = '''
if [ ! -f $HOME/.zcompdump ]; then
  autoload -Uz compinit && compinit
else
  local now=$(date +"%s")
  local updated=$(date -r $HOME/.zcompdump +"%s")
  local threshold=$((60 * 60 * 24))
  if [ ! -f $HOME/.zcompdump || $((${now} - ${updated})) -gt ${threshold} ]; then
    autoload -Uz compinit && compinit
  else
    # if there are new functions can be omitted by giving the option -C.
    autoload -Uz compinit && compinit -C
  fi
fi
'''

[plugins.enhancd]
github = "b4b4r07/enhancd"
apply = ["source"]

[plugins.zsh-abbr]
local = "/opt/homebrew/share/zsh-abbr"
use = ["zsh-abbr.zsh"]
apply = ["source"]

[plugins.dotfiles]
local = "~/.zsh"
use = ["*.zsh"]
apply = ["source"]

[plugins.dotfiles-private]
local = "~/.zsh.private"
use = ["*.zsh"]
apply = ["source"]
