shell = "zsh"
apply = ["source"]

[plugins.compinit]
inline = '''
local now=$(date +"%s")
local updated=$(date -r $HOME/.zcompdump +"%s")
local threshold=$((60 * 60 * 24))
if [ $((${now} - ${updated})) -gt ${threshold} ]; then
  autoload -Uz compinit && compinit
else
  # if there are new functions can be omitted by giving the option -C.
  autoload -Uz compinit && compinit -C
fi
'''

[plugins.enhancd]
github = "b4b4r07/enhancd"
apply = ["source"]

[plugins.ohmyzsh-lib]
github = "ohmyzsh/ohmyzsh"
dir = "lib"
use = ["{clipboard,completion,correction,directories,functions,git,grep,history,key-bindings,misc,spectrum,termsupport,theme-and-appearance}.zsh"]
apply = ["source"]

[plugins.ohmyzsh-plugins]
github = "ohmyzsh/ohmyzsh"
dir = "plugins"
use = ["{bundler/bundler,docker-compose/docker-compose,git/git,history/history,macos/macos,terraform/terraform,z/z}.plugin.zsh"]
apply = ["source"]

[plugins.dotfiles]
local = "~/.zsh"
use = ["*.zsh"]
apply = ["source"]

[plugins.dotfiles-private]
local = "~/.zsh.private"
use = ["*.zsh"]
apply = ["source"]
